# Generated by Django 2.2.5 on 2019-09-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetails',
            new_name='ProductDetail',
        ),
    ]
