# Generated by Django 2.2.5 on 2019-09-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190903_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='article_description',
            new_name='product_description',
        ),
    ]
